# -*- coding: utf-8 -*-
# (hook, the usual, verify?, travels?)

FORMATS = [
 ("The usual / not the usual",
  "Two columns. What's standard, then the version you were handed. The whole franchise in one shape — it turns a definition into a diagnosis, and the viewer checks their own paperwork while watching.",
  "“Four years, one year cliff. That's the usual. Six years with a two-year cliff is not a company, it's a holding pen.”"),
 ("The sentence you say back",
  "One moment, one line, delivered slowly enough to be written down. The highest-utility format you can make and the most re-watched.",
  "“When they say we'll make it right at the next round — 'happy to wait, can we put the number and the date in the offer?'”"),
 ("What they said / what it means",
  "Translation. Recruiter language, brand-side language, investor language, decoded. Works because these people all speak in the same eight euphemisms.",
  "“'We don't have budget' has five meanings and only one of them is no.”"),
 ("The number",
  "One benchmark, held on screen, no build-up. Shortest format, travels furthest, needs the most verification before you say it out loud.",
  "“Ninety days. That's how long you have to find the money after you leave.”"),
 ("Red flag / just unusual",
  "Calibration. Half of what scares people is standard and half of what looks standard should scare them. Being the person who can tell them apart is the whole authority claim.",
  "“Participating preferred isn't illegal. It's just expensive, and it's expensive to you specifically.”"),
 ("Ask this one thing",
  "A single question, plus what the answer tells you and what their face tells you. Self-contained, endlessly repeatable, works at any point in the series.",
  "“Ask what the total preference is ahead of you. They will tell you. Nobody ever asks.”"),
 ("The arithmetic, out loud",
  "Green screen, numbers appearing as you say them. Reserved for the four or five concepts that only land when someone watches the figure move.",
  "“One percent, three rounds, twenty percent each. Say it with me.”"),
 ("I was on the other side of this",
  "Your unfair advantage, used sparingly. Not a story format — a credential format. One sentence of it buys you the rest of the video.",
  "“I've written the brief that had your fee in it. Here's what was in the other half of the document.”"),
]

CHAPTERS = [
("You're being hired",
 "The moment with the most leverage and the least information. Almost everything here is askable and almost nobody asks.",
[
("0.1% sounds like nothing and might be worth more than 1% somewhere else",
 "Equity gets quoted three ways — percentage, share count, or dollar value at the last round. Which one they lead with tells you what the other two would reveal.", False, True),
("The creative discount is real and it has a number",
 "Non-technical roles are typically granted materially less equity than engineers at the same level and stage. It's convention, not policy, which means it's arguable.", True, True),
("Your title is a compensation instrument",
 "Equity bands are set by level, not by person. Negotiating from Senior Manager to Director usually moves more equity than any conversation about the grant itself.", True, False),
("Negotiate the vesting, not the number",
 "Four years with a one-year cliff is the default. A shortened cliff, monthly vesting from day one, or double-trigger acceleration are all askable and cost the company nothing today.", False, True),
("The offer letter isn't the document that matters",
 "The stock plan and the grant agreement carry the terms. They're usually sent after you accept. Ask for both before.", False, True),
("Ask what the last 409A was",
 "It's the price your options are struck at and they have the number. Whether they hand it over or get strange is itself the answer.", False, True),
("“We'll make it right at the next round”",
 "Worth nothing as a sentence. Worth something as a written number with a date and a trigger attached. Ask for the second version.", False, True),
("What “competitive” means when a recruiter says it",
 "Competitive against a benchmark they've chosen and won't name. Ask which dataset, which stage, which geography.", False, False),
("Signing bonus, salary, or equity — which to push on",
 "Depends on stage. Early: equity, because the rest is small anyway. Late: cash, because the equity is priced and the upside is mostly gone.", False, False),
("The four questions that change how they see you",
 "Preference stack, fully diluted count, last 409A, exercise window. Asking these reads as sophisticated rather than greedy, which is itself useful information about the company.", False, True),
]),

("You already signed something",
 "The paperwork most people read once, at the least sceptical moment of their lives.",
[
("Equity, options, RSUs, phantom — sorted by what they do to you",
 "At a private company pre-IPO, options are most common. RSUs arrive later. Phantom shows up in agencies, family businesses and anything not venture-backed — which is where a lot of brand and creative people actually work.", False, True),
("Phantom stock is a bonus wearing a costume",
 "It's a contractual promise to pay cash tied to a valuation. No ownership, no voting, no capital gains treatment, and it dies if the company decides it does. Agencies love it for exactly those reasons.", True, True),
("Your ninety-day window is the most expensive line in the contract",
 "Ninety days after you leave to exercise, or the options vanish. Some companies offer extended windows of up to ten years. Almost nobody asks which one they're on until they resign.", False, True),
("Find your cliff date and put it in your calendar",
 "One year from start. Leaving in month eleven means you worked a year for salary alone. Nobody at the company will ever remind you.", False, True),
("Dilution is not theft, and here is when it is",
 "Every round issues new shares and your percentage shrinks. That's normal. A pool refresh taken out of the pre-money, so existing holders absorb all of it, is normal too — and worth knowing you're absorbing.", False, False),
("Liquidation preference in one sentence",
 "Investors get their money back before anyone else sees a dollar. One-times non-participating is standard. Anything above that appears when a company raised from a position of weakness.", False, True),
("Participating preferred, plainly",
 "They take their money back and then also take their percentage of what's left. Double dip. Legal, not rare, and it moves the sale price at which you see anything.", False, True),
("The non-solicit is the clause that matters more than the non-compete",
 "In a lot of places non-competes are hard to enforce. Non-solicits are enforced routinely, and they're the ones that stop you taking your team or your clients.", True, False),
("You might not be allowed to show your own work",
 "Work-for-hire assigns everything, including the right to display it. The portfolio carve-out is almost always granted and almost never requested.", False, True),
("What happens to your equity if you go freelance for the same company",
 "Usually you stop vesting on the day the employment ends, even if the work continues. Continuity of work is not continuity of grant.", True, False),
("The AI clause nobody is reading yet",
 "Newer contracts contain language about generating derivative or synthetic material from delivered work. Worth finding out whether you've licensed them the right to produce more of you without you.", False, True),
]),

("You're setting your price",
 "Where the money is actually won or lost for most people in this audience — repeatedly, quietly, for years.",
[
("You're quoting cost-to-serve and calling it a rate",
 "Three different numbers: what it costs you to do it, what the market pays, what the outcome is worth to them. Most people quote the first and never find out the third.", False, True),
("What the agency charges the client for the work you do",
 "Agencies bill a multiple of salary cost to cover overhead, benefits, management and margin. Going freelance at your old day rate means charging a fraction of what the work sells for.", True, True),
("How many billable days you actually have",
 "Not 260. Subtract holiday, admin, pitching, invoicing, sick days and the weeks nothing lands. Solo practices run well under full utilisation and the annual number is the one that matters.", True, True),
("The day rate is a trap and here's the arithmetic",
 "Day rates invite counting days, cap your upside at your calendar, and punish you for getting faster. Project fees pay you for being good at this.", False, True),
("Kill fees exist and you should have one",
 "A percentage of the remaining fee if they cancel mid-project. Standard in production and editorial, rare in consulting only because consultants don't ask.", True, True),
("Net 60 is an interest-free loan you're extending",
 "Large companies default to 30, 60 or 90 day terms set by procurement, not by your client. It's negotiable more often at the contract stage than at the invoice stage.", False, True),
("Quote a range only if you'd be happy with the bottom of it",
 "They will hear the bottom. It isn't a negotiation tactic, it's a discount you offered before being asked.", False, True),
("Deposits: 50/50, or 30/40/30",
 "Money up front is standard practice, not an insult. A deposit is the thing that makes a cancellation expensive for them instead of only for you.", False, False),
("Raising rates on a client you already have",
 "Tie it to a date and a new scope rather than to your feelings about the work. The re-scope conversation is easier than the raise conversation and produces the same number.", False, True),
("The qualifying questions before you scope anything",
 "Budget range, decision-maker, timeline, and what happens if they do nothing. Scoping before you know these is unpaid work.", False, False),
]),

("You're doing a deal",
 "Your own ground. The part where you've read the brief from the other side.",
[
("You sold a post. They bought an asset.",
 "Paying for a post buys the post, organic, on your channel. Running it as an ad is buying media against something you made, and it's a separate line with a separate number.", False, True),
("Search the contract for the word perpetuity",
 "Term, territory, channel and spend are the four axes that price usage. Perpetuity removes one of them entirely. If it's in there and the fee didn't move, the fee was wrong.", False, True),
("Whitelisting, explained by what it costs you",
 "They run paid media through your handle so it reads as you. Your account carries the endorsement and their budget carries the reach. Price it as endorsement, not as a technical permission.", False, True),
("Exclusivity is forgone revenue, not a favour",
 "Price it as the deals you won't be able to take in that window. Twelve months of category exclusivity when you book four of those a year is most of your year.", False, True),
("Which budget is paying you sets your ceiling",
 "Brand, performance, innovation, trade, or the founder's discretionary line. Same deliverable, four different tolerances, four different approval paths.", False, True),
("The person emailing you cannot say yes",
 "Signing authority sits at a threshold, and the threshold is usually lower than people assume. Write the email that survives being forwarded upward, because it will be.", False, True),
("“We don't have budget” has five meanings",
 "Not in this pot, not this quarter, not at this priority, no internal champion, or genuinely none. Four of the five are timing problems rather than a no.", False, True),
("Seeding: on-ramp or unpaid labour",
 "Seeding is normal and often genuinely useful early. It stops being an on-ramp the moment the brand is running paid media and still sending product instead of a fee.", False, True),
("EMV is a number brands know is soft",
 "Earned media value is a modelled figure with no agreed methodology. It appears in decks because something has to. Knowing it's soft changes how you argue about your own reporting.", True, False),
("Ask what the client is being charged for you",
 "When an agency sits between you and the brand, there's a markup. It's normal. Knowing roughly what it is tells you where your rate actually sits in the deal.", True, True),
("Rev share without a floor is a free option",
 "If you don't control the landing page, the pricing, the stock, or the attribution window, you've taken performance risk on decisions you can't influence.", False, True),
("Why deals die internally, and how to keep yours alive",
 "Rarely price. Usually a champion who moved, a quarter that closed, a legal queue, or nobody senior who could describe why you specifically.", False, False),
("What gets you re-booked",
 "Being easy to run through a legal and finance process. Unglamorous, commercially decisive, and almost never discussed as a skill.", False, True),
]),

("You're reading the room",
 "The part that isn't in any contract and decides most outcomes.",
[
("Read the org chart for authority, not title",
 "Economic buyer, champion, blocker. Titles tell you rank. Only one of those three can actually release money.", False, True),
("Information asymmetry is the real currency",
 "Everything in this series is known by someone in the room already. The advantage isn't intelligence, it's having been in the room before.", False, False),
("What you're owed when you're paid in access",
 "Access, proximity, information and optionality are real compensation and should be priced. The tell that it's exposure with extra steps: remove the access and see if you'd still take it.", False, True),
("Set the walk-away number before the call",
 "Decide it when you're calm, write it down, and don't revise it while someone is talking to you.", False, True),
("Negotiating when you actually need the money",
 "The hardest version, and the one nobody makes content about. What you can still control: silence, sequencing, and what you ask before you answer.", False, True),
("Small industry, long memory",
 "How you leave is a commercial asset. The people on the other side of your next three deals already know someone you've worked with.", False, False),
("Sponsorship versus mentorship",
 "A mentor tells you things. A sponsor says your name when you aren't there. Only one of them changes your income.", False, True),
]),

("You're building something of your own",
 "Where fuck-you money actually comes from for this audience, more often than from a grant.",
[
("Income stops when you do. What doesn't?",
 "The six-month test: if you stopped for half a year, what still earns? That list is the asset and everything else is a job with better branding.", False, True),
("What someone is actually buying if they buy your practice",
 "Contracts, IP, audience, systems and team. If the answer is “me”, there's nothing to sell, which is a fine choice as long as it's a choice.", False, True),
("Service, product, platform — the honest economics",
 "Each step trades margin for leverage and adds a completely different job. Most people skip the part where the job changes.", False, False),
("The newsletter is the asset. The follower count is the weather.",
 "Owned distribution can be moved, sold and valued. Rented distribution can be halved overnight by someone else's product decision.", False, True),
("Why service businesses sell for so much less than product businesses",
 "Multiples track how much of the revenue survives the founder leaving. That's the whole explanation and it's also the to-do list.", True, True),
("Licensing your own frameworks",
 "If you explain the same thing to every client, it's a product you're giving away inside a service you're discounting.", False, True),
("The advisor deal: what they're buying is your name on the deck",
 "Standard advisor grants are small and vest over one to two years. Perfectly fine — as long as you know that's the trade and price the rest accordingly.", True, True),
("Four questions before you take equity instead of cash",
 "Preference stack, amount raised against it, last 409A, and what happens to your grant in an acquihire. Same four questions as the job offer, because it's the same instrument.", False, True),
("Small cheques: what a brand person brings that a VC doesn't",
 "Distribution, positioning, and the ability to tell whether the thing is actually good. Under-priced by the people who have it.", False, False),
]),

("Money actually moves",
 "The endings. Most people only picture one of them.",
[
("Five endings, not one",
 "IPO, strategic acquisition, acquihire, private equity roll-up, or private forever. Your grant behaves differently under each and most people have only modelled the first.", False, True),
("Acquihire: the team is the asset and the product gets switched off",
 "Common, rarely announced as such, and the outcome where employee equity most often goes to nothing while senior people are made whole through retention packages.", True, True),
("Retention pools are carved out of the purchase price",
 "Which means the headline number and the amount available to shareholders are different numbers, and being inside the pool matters more than your grant does.", True, True),
("Earnouts: why founders stay two more years looking miserable",
 "Part of the price is contingent on hitting targets after the sale. It's why the acquisition number in the press release is often not the number anyone receives.", False, True),
("Secondaries: how people get paid before an IPO",
 "The company organises a window, existing shares change hands, no new money enters the business. Increasingly the main way private-company employees see cash.", False, True),
("Sold for two hundred million, team got nothing, nobody did anything wrong",
 "The preference stack was in the documents from the beginning. This is the single most useful thing in the whole series and it takes forty seconds.", False, True),
("Borrowing against equity, including the part nobody says",
 "You can turn illiquid shares into cash by giving someone a claim on them. If the valuation falls the loan doesn't, and the collateral is the thing you were trying to keep.", False, True),
("What happens to unvested shares in each exit",
 "Usually they're assumed, converted, or cancelled, and which one is decided by the acquirer, not by you. Double-trigger acceleration is the clause that protects against the third.", False, False),
("You got the cheque. The first three decisions.",
 "Tax owed and when, what's genuinely liquid versus locked, and the six months of doing nothing that almost everyone says afterwards they wish they'd taken.", True, True),
]),
]
