# -*- coding: utf-8 -*-
# Domain map data. (name, kicker, level, [ (cluster, [units], [questions]) ])
# level: ground | adjacent | translation

DOMAINS = [
("The capital stack",
 "Where the money exists before anyone spends it. Every brief you ever receive was shaped by this.",
 "translation", [
  ("How a fund actually works",
   ["LPs, GPs, and whose money it really is", "The 2-and-20 structure", "Fund lifecycle: deploy, support, harvest",
    "Why a fund needs one 100x, not ten 2x", "Vintage year and why it decides your client's mood"],
   ["Why did this brand suddenly stop spending on anything unmeasurable?",
    "What does it mean that my client's investor is 'raising their next fund'?"]),
  ("The rounds, and what each one is buying",
   ["Pre-seed / seed: buying a bet on the founder", "Series A: buying proof the thing repeats",
    "Series B and beyond: buying a machine that scales", "Bridge, extension, and what they signal",
    "Down rounds, flat rounds, recaps"],
   ["What is this company being asked to prove in the next 18 months?",
    "How do I read a funding announcement for what it doesn't say?"]),
  ("Money that isn't venture",
   ["Bootstrapping and the discipline it buys", "Revenue-based financing", "Venture debt and when it bites",
    "Private equity: the other clock entirely", "Family money and the invisible head start",
    "Grants, accelerators, and what they actually cost you"],
   ["Which of these is my client on, and what does it make them afraid of?"]),
  ("What capital does to behaviour",
   ["Why VC-backed brands over-invest in growth and under-invest in brand",
    "Why PE-owned brands cut the thing you were hired for", "The 18-month runway and the Q3 panic",
    "Why founders get strange in year seven"],
   ["When a client goes quiet or cheap, what's happening upstairs?",
    "Should I be pitching brand work to a company nine months from a raise?"]),
 ]),

("What equity actually is",
 "Four words hiding four variables. The vocabulary you need before anyone offers you any.",
 "translation", [
  ("The instruments",
   ["Common vs preferred stock", "Options (ISO, NSO) and what exercising means", "RSUs and why they're different",
    "Phantom equity, SARs, profit interests", "'We'll sort it out later' — the non-instrument"],
   ["What was I actually offered, in one sentence?",
    "Is the thing in my offer letter a share, a promise, or a vibe?"]),
  ("The numbers attached to it",
   ["Strike price", "409A valuation and FMV", "Preferred price vs common price and the gap between them",
    "Fully diluted share count — the denominator nobody gives you"],
   ["What is one of my shares worth today, and who decided that?",
    "Why is the price investors paid different from my strike?"]),
  ("Time",
   ["Four-year vest, one-year cliff", "Monthly vs quarterly vesting after the cliff",
    "Acceleration: single trigger vs double trigger", "Post-termination exercise windows — the 90-day trap",
    "Extended exercise windows and who offers them"],
   ["What is my cliff date and does anyone here know it?",
    "If I leave, how long do I have and what will it cost me?"]),
  ("Dilution",
   ["Why every round issues new shares", "Option pool refreshes and the pre-money pool shuffle",
    "Running a percentage across four rounds", "When dilution is fine and when it isn't"],
   ["Is the pie growing faster than my slice is shrinking?"]),
  ("The preference stack",
   ["1x non-participating — the standard", "Participating preferred / double dip", "2x and 3x preferences and when they appear",
    "Seniority: who gets paid before whom", "Why a $200m sale can pay staff nothing"],
   ["What is the total preference ahead of me?",
    "At what sale price do I see a single dollar?"]),
  ("Cap table literacy",
   ["Reading a cap table", "Founder / investor / pool / employee split at each stage",
    "SAFEs and notes as invisible future dilution", "What 'fully diluted' includes and excludes"],
   ["What am I allowed to ask, and what does their reaction tell me?"]),
 ]),

("Getting paid out",
 "Paper becomes money, or doesn't. The full set of endings, not just the one everyone pictures.",
 "translation", [
  ("Liquidity before an exit",
   ["Secondaries: selling existing shares to a new buyer", "Company-run tender offers",
    "Why a company runs one (retention, not generosity)", "What 'oversubscribed' publishes about price",
    "Transfer restrictions and rights of first refusal"],
   ["Can I sell, to whom, and does the company get a veto?"]),
  ("The exits",
   ["IPO and the lockup", "Direct listing", "Strategic acquisition", "Acquihire — the one where the team is the asset",
    "PE roll-up", "Asset sale", "Staying private forever as a real strategy"],
   ["What happens to my specific grant under each of these?"]),
  ("The clauses that decide the number",
   ["Earnouts and why founders stay two more years", "Escrow and holdback",
    "Retention pools carved out of the purchase price", "Change-of-control provisions"],
   ["Is the headline price the price?"]),
  ("Borrowing against it",
   ["Loans secured on private shares", "Who lends and at what LTV", "What happens if the valuation falls",
    "Why this is a trade, not a cheat code"],
   ["What am I giving someone a claim on, and under what conditions do they take it?"]),
 ]),

("How brands actually budget",
 "The bridge between the money and you. Most creative people never learn this and it costs them every negotiation.",
 "adjacent", [
  ("The pots",
   ["Brand vs performance vs innovation vs trade", "Founder's discretionary and the CEO's pet line",
    "Working vs non-working spend", "Agency retainer vs project vs in-house capacity",
    "Why the same deliverable prices differently out of different pots"],
   ["Which pot is paying me, and what is it measured on?",
    "Can this budget move, or is it locked to a line item?"]),
  ("The calendar",
   ["Annual planning and when decisions are actually made", "Use-it-or-lose-it and the Q4 scramble",
    "Fiscal years that aren't calendar years", "When to pitch versus when to invoice"],
   ["Am I pitching into a planning window or a dead month?"]),
  ("The gatekeepers",
   ["Coordinator, manager, director, VP — who can say yes at what number",
    "Procurement, MSAs, preferred supplier lists", "Legal as the real timeline",
    "Agency-of-record relationships and where you fit around them",
    "Why the person emailing you cannot approve you"],
   ["Who has signing authority at my number?",
    "What document gets forwarded upstairs, and is my number in it?"]),
  ("What 'no budget' means",
   ["No budget in this pot", "No budget this quarter", "No budget at this priority",
    "No internal champion", "Actually no budget"],
   ["Which of the five is this, and which of them is a timing problem rather than a no?"]),
 ]),

("Creator partnerships",
 "The commercial engine. The widest domain here and the one you teach from the room rather than from research.",
 "ground", [
  ("The spectrum of deals",
   ["Seeding and gifting", "Paid single post", "Multi-post campaign", "Ambassadorship and retainer",
    "Affiliate and commission", "Equity or advisory", "Co-branded product", "Acquisition of the creator's brand"],
   ["Where on this spectrum is the brand actually trying to be, and do they know?"]),
  ("Seeding economics",
   ["What a seeding programme costs to run properly", "Hit rate and why brands mis-measure it",
    "Product cost vs the labour of the programme", "When seeding is generous and when it's unpaid work",
    "The tipping point where seeding should become paid"],
   ["Is this brand seeding because it's early, or because it's cheap?",
    "What would make me post about something for free, honestly?"]),
  ("Setting a rate",
   ["CPM logic", "Engagement-rate logic", "Value-to-brand logic", "Cost-to-serve for the creator",
    "Why none of these is what actually happens in the room", "Rate cards and when to have one"],
   ["What am I actually charging for — reach, craft, endorsement, or exclusivity?"]),
  ("Usage rights",
   ["Organic only", "Paid amplification", "Whitelisting and Spark Ads", "Brand-channel repurposing",
    "Term, territory, channel, spend as the four pricing axes", "Perpetuity and why it's never free",
    "What happens when a brand runs your face after you've stopped working with them"],
   ["Did my rate move when the usage did?",
    "What does this contract let them do in eighteen months?"]),
  ("Exclusivity",
   ["Category lockouts", "Competitor lists — narrow vs open-ended", "Duration and the cost of a year",
    "Pricing exclusivity as forgone revenue, not as a favour"],
   ["How many deals in this category do I book a year, and what does this clause cost me?"]),
  ("Performance and rev share",
   ["Affiliate structures and typical rates", "Rev share with and without a floor",
    "Who controls the conversion surface", "Attribution windows and who owns the data",
    "When a performance deal is a free call option the brand bought off you"],
   ["Can I see the reporting, and is there a floor?"]),
  ("The contract",
   ["Approvals and revision rounds as hidden cost", "Kill fees", "Payment terms: net 30 / 60 / 90",
    "Morality and conduct clauses", "Exclusivity of opinion and the honesty problem", "FTC and disclosure",
    "Indemnity — what you're promising about your own content"],
   ["What do I redline first? What do I never sign?"]),
  ("The other side of the table",
   ["What the brand-side person is measured on", "Why briefs are written the way they are",
    "The brief behind the brief", "Why deals die internally", "What makes a creator easy to re-book"],
   ["What does saying yes to me do for this person's quarter?"]),
  ("Representation",
   ["Agent vs manager vs talent agency", "Commission structures and what they should cover",
    "When representation adds value and when it adds a layer", "Negotiating your own deals"],
   ["What is this person doing that I couldn't, and is it worth 20%?"]),
  ("Measurement",
   ["Reach, engagement, EMV and why EMV is largely fake", "Incrementality and why brands rarely test it",
    "Brand lift studies", "What actually gets a campaign renewed"],
   ["What number will be in the deck that decides whether I'm re-booked?"]),
 ]),

("Contracts and what you own",
 "Where careers quietly leak. Short domain, high consequence.",
 "adjacent", [
  ("Ownership of the work",
   ["Work-for-hire vs licensing", "Assignment of IP", "Moral rights and waiver",
    "Portfolio carve-outs — the clause you should always ask for", "Case study and credit rights"],
   ["Am I allowed to show this work, and from when?"]),
  ("Restrictions on you",
   ["NDAs — reasonable vs absurd", "Non-compete", "Non-solicit", "Exclusivity of service vs exclusivity of category"],
   ["What does this stop me doing for the next two years?"]),
  ("Getting paid",
   ["Deposit structures", "Milestone payments", "Late payment terms and interest",
    "Kill fees and termination for convenience", "Chasing an invoice without damaging the relationship"],
   ["What happens to my money if they cancel in week three?"]),
  ("New territory",
   ["AI-generated elements in a deliverable and who owns them", "Likeness, voice and synthetic use clauses",
    "Training-data permissions buried in usage terms"],
   ["Does this contract let them generate more of me without me?"]),
 ]),

("Pricing yourself",
 "The applied version of everything above, for one person with a practice.",
 "ground", [
  ("Three different numbers",
   ["Cost-to-serve: time times what you need", "Rate: the market's shape", "Value: what the outcome is worth to them",
    "The gap between cost-to-serve and value is the whole conversation"],
   ["Which of the three am I quoting, and which should I be?"]),
  ("The instruments",
   ["Day rate and how it caps you", "Project fee and why it rewards speed", "Retainer: predictability for flexibility",
    "Equity or revenue share instead of cash", "Hybrids and when they're worth the complexity"],
   ["When a client asks for my day rate, what are they planning to do with it?"]),
  ("Scope",
   ["The scope that names what's excluded", "Revision limits", "Scope creep and the re-scope conversation",
    "Pausing work versus renegotiating"],
   ["What does this scope explicitly not include, in writing?"]),
  ("Delivering the number",
   ["Number first, naked, no padding", "The silence after", "Ranges as a tell",
    "Discounting: when it's strategic and when it's fear", "Raising rates on an existing client"],
   ["What am I about to say before the figure, and why am I saying it?"]),
  ("The business behind the practice",
   ["Utilisation maths for a solo practice", "Pipeline versus capacity", "Qualifying a lead before scoping",
    "Saying no, and the cost of a bad yes"],
   ["How many billable days do I really have this year?"]),
 ]),

("Platforms and distribution",
 "Who owns the pipe between you and the person. Increasingly the only question that matters.",
 "ground", [
  ("Rented versus owned",
   ["Follower counts as rented", "Email lists, podcast feeds, communities as owned",
    "Platform payout programmes and why they aren't a business", "Algorithmic risk and de-platforming"],
   ["If this platform halved my reach tomorrow, what would I still have?"]),
  ("Distribution as the moat",
   ["Why the worse product with better distribution wins", "Retail and shelf as distribution",
    "Wholesale versus DTC economics", "Borrowed audiences: collabs, co-marketing, guesting",
    "Why founders over-invest in product"],
   ["What is this brand's real distribution advantage, if any?"]),
  ("Media as an asset class",
   ["Newsletters and shows that get acquired", "What a buyer values in a media property",
    "Audience quality versus audience size", "Community as durable demand"],
   ["Is what I'm building a channel, a brand, or a business?"]),
 ]),

("Turning work into an asset",
 "The difference between a very good job and a thing that exists without you.",
 "adjacent", [
  ("Income versus asset",
   ["Revenue that stops when you stop", "Revenue that doesn't",
    "What a buyer is actually buying: contracts, IP, audience, team, systems",
    "The six-month test"],
   ["If I stopped for six months, what still earns?"]),
  ("Productising",
   ["Service to product to platform", "Licensing your own frameworks",
    "Courses, cohorts, membership — the honest economics", "Templates and tools"],
   ["What do I explain so often it should be a product?"]),
  ("Equity for service",
   ["Standard advisor grants and vesting", "What the company is really buying (usually your name)",
    "Due diligence you can actually do", "When to take cash instead"],
   ["Would I put my own money into this company at this valuation?"]),
  ("Valuation of small things",
   ["How service businesses are valued", "How media properties are valued", "How product businesses are valued",
    "Multiples and why yours is lower than you think"],
   ["What multiple applies to what I've built, and why that one?"]),
 ]),

("Power",
 "The part that isn't money and decides most outcomes. The domain nobody puts in a syllabus.",
 "ground", [
  ("Who actually decides",
   ["Reading an org chart for authority rather than title", "Economic buyer versus champion versus blocker",
    "Where deals die and why it's rarely the price", "Building an internal champion"],
   ["Who in this building can say yes, and have I ever spoken to them?"]),
  ("Rooms",
   ["What a room is: where price is set before it's announced", "How rooms form and reproduce",
    "Getting in by being useful to someone already inside", "Delhi rooms and New York rooms run on different currencies",
    "What you owe a room once you're in it"],
   ["Which room is this decision actually made in?"]),
  ("Information as currency",
   ["Asymmetry as the real advantage", "What you learn by being early", "Sharing information as a compounding strategy",
    "Discretion and why it buys more than access"],
   ["What do I know that they don't, and what's it worth?"]),
  ("Non-cash compensation",
   ["Access, proximity, information, optionality", "Pricing each honestly",
    "Proximity as product", "The tell that you're being paid in exposure with extra steps"],
   ["Would I take this if the access were removed and the money stayed?"]),
  ("Negotiation posture",
   ["BATNA and actually having one", "The walk-away number, set before the call",
    "Silence as a tool", "Anchoring", "Negotiating when you need the money"],
   ["What's my alternative if this falls through, and have I built one?"]),
  ("Reputation",
   ["Small-industry effects and the long memory", "Sponsorship versus mentorship",
    "Being easy to work with as a commercial asset", "How to leave a client badly and what it costs"],
   ["Who would vouch for me without being asked?"]),
 ]),
]

CUTS = [
 ("The corporate baddie's first year",
  "For someone in-house who wants to stop being a passenger. Ordered by what they hit first, not by theory.",
  ["Which pot is paying for this", "Who can actually say yes", "What 'no budget' means",
   "The four words in 'I have equity'", "Your cliff date", "Options vs RSUs",
   "Dilution, arithmetically", "The preference stack", "Five questions before you take the job",
   "Three levers in a comp conversation", "Usage rights", "Exclusivity",
   "What a kill fee is for", "Portfolio carve-outs", "The brief behind the brief",
   "What your counterpart is measured on", "EMV is fake", "Rate vs value vs cost-to-serve",
   "The number goes naked", "Raising rates on an existing client", "Rented vs owned distribution",
   "Income vs asset", "The six-month test", "Advisor grants", "Secondaries and tenders",
   "What happens to your grant in an acquihire", "Economic buyer vs champion", "BATNA",
   "Proximity as product", "What you'd tell yourself at 25"]),
 ("Follow the money",
  "The flow, origin to compounding. Most coherent as a binge; hardest to enter mid-series.",
  ["Where the money starts: how a fund works", "What each round is buying", "Money that isn't venture",
   "What capital does to a brand's behaviour", "How that becomes a marketing budget",
   "The four pots", "The planning calendar", "The gatekeepers", "How budget reaches an agency",
   "How it reaches a creator", "Seeding economics", "Setting a rate", "Usage rights",
   "Exclusivity", "Performance deals", "What the contract does to all of it",
   "What you own at the end", "Getting paid: terms and kill fees", "From fee to practice",
   "Utilisation maths", "From practice to asset", "What a buyer buys", "Equity instead of cash",
   "What equity is", "What it's worth today", "Dilution", "The preference stack",
   "Secondaries", "The five exits", "Where the money ends up"]),
 ("The deal",
  "Heaviest on partnerships and contracts. Closest to the consulting practice, most directly commercial.",
  ["The spectrum: seeding to acquisition", "Why brands seed", "When seeding should become paid",
   "Which pot is paying", "Who can say yes", "The brief behind the brief",
   "What your counterpart is measured on", "Four ways to price a post", "Rate cards",
   "Usage rights: the four axes", "Whitelisting", "Perpetuity", "Exclusivity as forgone revenue",
   "Competitor lists", "Affiliate vs rev share", "Floors and reporting", "Attribution and who owns data",
   "Approvals as hidden cost", "Kill fees", "Payment terms", "Morality clauses", "FTC",
   "Indemnity", "Work-for-hire vs licensing", "Portfolio carve-outs", "Agent vs manager",
   "What gets you re-booked", "Why deals die internally", "Walking away", "The number goes naked"]),
]
